FROM docker:git

LABEL maintainer="William Bridge <ngaswilly77@gmail.com>"

# Default helm version and helm base url
ENV VERSION="3.10.1"
ENV BASE_URL="https://get.helm.sh"

# Install packages : openssh-server openjdk11 wget curl helm
RUN case `uname -m` in \
        x86_64) ARCH=amd64; ;; \
        armv7l) ARCH=arm; ;; \
        aarch64) ARCH=arm64; ;; \
        ppc64le) ARCH=ppc64le; ;; \
        s390x) ARCH=s390x; ;; \
        *) echo "un-supported arch, exit ..."; exit 1; ;; \
    esac && \
    apk add --update --no-cache openssh-server openjdk11 wget curl && \
    wget ${BASE_URL}/helm-v${VERSION}-linux-${ARCH}.tar.gz -O - | tar -xz && \
    mv linux-${ARCH}/helm /usr/bin/helm && \
    chmod +x /usr/bin/helm && \
    rm -rf linux-${ARCH}

# Add jenkins user to the image
RUN adduser -D jenkins

# Set password for the jenkins user
RUN echo "jenkins:jenkins" | chpasswd

# Generate host keys
RUN ssh-keygen -A

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]